rabbit_login: guest
rabbit_passw: guest
rabbit_port: 5673
rabbit_host: localhost
queue_name: frames_extraction
result_queue_name: frames_extraction_result
storage_path: /storage1/mrowl/image_storage/videos/