rabbit_login: guest
rabbit_passw: guest
rabbit_port: 5672
rabbit_host: localhost
queue_name: frames_extraction
result_queue_name: frames_extraction_result
storage_path: /storage/project/static/images/tmp