version: "2.3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - main

  ffmpeg:
    image: moderation
    depends_on:
      - redis
    volumes:
      - /storage1/mrowl/image_storage:/image_storage
    links:
      - redis
    environment:
      - DOCKER_USE=1
      - STORAGE_PATH=/image_storage
      - AWS_ENDPOINT_URL= "${DATABASE_URL}"
      - AWS_ACCESS_KEY_ID= "${miniouser}"
      - AWS_SECRET_ACCESS_KEY= "${AWS_SECRET_ACCESS_KEY}"
    networks:
      - main

  improsch:
    image: improsch
    depends_on:
      - redis
    volumes:
      - /storage1/mrowl/image_storage:/image_storage
      - /storage1/mrowl/dedup_index:/dedup_index
    environment:
      - DOCKER_USE=1
    networks:
      - main
    runtime: nvidia

  scoring:
    image: scoring
    depends_on: 
      - redis
    volumes:
      - /storage1/mrowl/scoring_models:/models_storage
      - /storage1/mrowl/image_storage:/storage
    environment:
      - IN_DOCKER=1
      - MODELS_STORAGE=/models_storage
    networks:
      - main
    runtime: nvidia


networks:
  main:
