version: "3"

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - main

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - main

  ffmpeg:
    image: moderation
    depends_on:
      - redis
    volumes:
      - ${IMAGE_STORAGE}:/image_storage
    links:
      - redis
    environment:
      - DOCKER_USE: 1
      - STORAGE_PATH: /storage
      - AWS_ENDPOINT_URL: "${DATABASE_URL}"
      - AWS_ACCESS_KEY_ID: "${miniouser}"
      - AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    networks:
      - main

  improsch:
    image: improsch
    depends_on:
      - rabbit
    volumes:
      - ${IMAGE_STORAGE}
      - ${DEDUP_INDEX}
    networks:
      - main
    runtime: nvidia


networks:
  main: