storage_path: /home/s/Documents/xxx/tmp/image_storage
dedup_index_path: /home/s/Documents/xxx/tmp/tmp_storage
saving_pool_size: 3
dedup_batch_size: 64
rabbit_login: guest
rabbit_passw: guest
rabbit_port: 5672
rabbit_host: 127.0.0.1
