version: "3.7"

services:
    rabbit:
        image: rabbitmq:3-management
        ports:
            - 15673:15672
            - 5673:5672
    video_handler:
        image: video_handler
        depends_on: 
            - rabbit